### ISSUE TITLE
Reverse proxy failing for upstream with invalid certificate

### ISSUE THREAD

**Issue by Sebosek** [ProxyKit/ProxyKit#221]
Hi,

upstream service (test environment) is using an unsigned certificate. The request however failing with `InvalidOperationException: The stream was already consumed. It cannot be read again.` in case of upstream service returns 301 Moved permanently.

Here is my startup class.
```csharp
public class Startup
{
    private readonly IConfiguration _configuration;
    
    public Startup(IConfiguration configuration)
    {
        _configuration = configuration;
    }
    
    // This method gets called by the runtime. Use this method to add services to the container.
    // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
    public void ConfigureServices(IServiceCollection services)
    {
        services.Configure<AdminConfig>(_configuration.GetSection("Admin"));

        services.AddProxy(httpClientBuilder =>
            httpClientBuilder.ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true
            }));
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseRouting();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGet("/", async context =>
            {
                await context.Response.WriteAsync("Runtime proxy up & running!");
            });
            
            endpoints.MapGet("/admin", async context =>
            {
                var options = new JsonSerializerOptions {WriteIndented = true};
                var config = app.ApplicationServices.GetService<IOptions<AdminConfig>>();
                
                await context.Response.WriteAsync(JsonSerializer.Serialize(config.Value, options));
            });
        });
        app.RunProxy(context =>
        {
            var config = app.ApplicationServices.GetService<IOptions<AdminConfig>>();
            var forwards = config.Value.Forwards;
            var path = context.Request.Path;

            foreach (var forward in forwards)
            {
                var regex = new Regex(forward.Path);
                if (!path.HasValue || !regex.IsMatch(path.Value)) continue;
                
                var forwardContext = context.ForwardTo(forward.Proxy.Host);
                if (!forward.Proxy.Cors)
                {
                    return forwardContext.Send();
                }
                
                // cors magic TBD
                return forwardContext.Send();
            }

            return null;
        });
    }
}
```

And forward configuration.
```
  "Admin": {
    "Forwards": [
      {
        "name": "services",
        "path": "^/services",
        "map": null,
        "proxy": {
          "host": "https://10.10.30.187",
          "cors": true
        }
      },
      {
        "name": "google",
        "path": "^/google",
        "map": null,
        "proxy": {
          "host": "https://google.com",
          "cors": true
        }
      }
    ]
  },
```

Full exception details:
```System.Net.Http.HttpRequestException: An error occurred while sending the request.

 ---> System.InvalidOperationException: The stream was already consumed. It cannot be read again.

   at System.Net.Http.StreamContent.PrepareContent()

   at System.Net.Http.StreamContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)

   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at ProxyKit.ForwardContext.Send()

   at ProxyKit.ProxyMiddleware`1.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Sebosek** [comment]
Closing in favor of a bug report.
